name: cryptocurrency_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.3.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  google_fonts: 2.1.0
  nb_utils: ^4.4.11

  #Firebase
  firebase_core: ^1.10.0
  firebase_analytics: ^8.3.4
  firebase_crashlytics: ^2.3.0
  google_mobile_ads: ^0.13.6
  onesignal_flutter: ^3.2.7
  firebase_auth: ^1.1.1
  firebase_storage: ^8.0.4
  cloud_firestore: ^3.1.0

  # AppAnimations and functionality
  animated_bottom_navigation_bar: ^0.3.2
  shimmer: ^2.0.0
  lottie: ^1.2.1
  cached_network_image: ^3.1.0+1
  number_slide_animation: ^0.2.1
  readmore: ^2.1.0
  flutter_neumorphic: ^3.1.1

  #Charts
  chart_sparkline: ^1.0.6
  syncfusion_flutter_charts: ^19.3.48

  # Storage
  sqflite: ^2.0.0+4

  #API calling
  http: ^0.13.4
  html: ^0.15.0
  flutter_html: ^2.1.5
  intl: ^0.17.0

  # System Info
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.12
  share_plus: ^3.0.4
  wakelock: ^0.5.6

  # State Management Technique
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2

  google_sign_in: ^5.2.1

  image_picker: ^0.8.4+4

  flutter_slidable: ^1.1.0

  flutter_localizations:
    sdk: flutter
  flutter_facebook_auth: ^4.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  # State Management Technique
  build_runner: ^2.1.2
  mobx_codegen: ^2.0.3
#flutter packages pub run build_runner build --delete-conflicting-outputs
flutter:

  uses-material-design: true

  assets:
    - images/
    - lang/
    - assets/
    - images/chart_images/
    - images/app_images/
    - images/social_images/
